language: cpp
sudo: required
dist: xenial
compiler:
- gcc
os:
- linux
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git libboost-all-dev tbb-devel cmake
script:
    - wget https://root.cern/download/root_v6.16.00.Linux-ubuntu16-x86_64-gcc5.4.tar.gz
    - tar xzf root_v6.16.00.Linux-ubuntu16-x86_64-gcc5.4.tar.gz
    - source root/bin/thisroot.sh
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - cd tests
    - ctest
